"""empty message

Revision ID: 847cccb2cb9d
Revises: affad6bc540b
Create Date: 2023-08-16 00:16:40.987629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847cccb2cb9d'
down_revision = 'affad6bc540b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_message_reaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('reaction_type', sa.VARCHAR(), nullable=False),
    sa.Column('reaction_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_message_reactions')
    # ### end Alembic commands ###
