"""empty message

Revision ID: b737c93489db
Revises: ca080559e379
Create Date: 2023-01-27 09:11:03.588628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b737c93489db'
down_revision = 'ca080559e379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_votes', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_votes', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
