"""empty message

Revision ID: b96d82202e98
Revises: 260607d80448
Create Date: 2023-09-01 01:11:53.245074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96d82202e98'
down_revision = '260607d80448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('name_format', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'name_format')
    # ### end Alembic commands ###
