"""empty message

Revision ID: 3f3d1d49a626
Revises: 3f2ee41f633f
Create Date: 2023-01-21 09:59:17.779763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3d1d49a626'
down_revision = '3f2ee41f633f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PostVotes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('posts', sa.Column('votes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('karma', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'karma')
    op.drop_column('posts', 'votes')
    op.drop_table('PostVotes')
    # ### end Alembic commands ###