"""empty message

Revision ID: d9b8b2f17643
Revises: e237bceab2c4
Create Date: 2023-01-21 23:52:04.910977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b8b2f17643'
down_revision = 'e237bceab2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'votes')
    # ### end Alembic commands ###