"""empty message

Revision ID: df167b0b8e6e
Revises: 1aeda2490630
Create Date: 2023-01-23 23:27:34.224701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df167b0b8e6e'
down_revision = '1aeda2490630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('img_url', sa.String(length=255), nullable=True))
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('posts', 'img_url')
    # ### end Alembic commands ###