"""empty message

Revision ID: 01c8908170e0
Revises: 7c54bd156e53
Create Date: 2023-09-10 11:38:19.154037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c8908170e0'
down_revision = '7c54bd156e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_settings', sa.Column('custom_banner_color', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_settings', 'custom_banner_color')
    # ### end Alembic commands ###
