"""empty message

Revision ID: 9daba46aba75
Revises: df98876c986a
Create Date: 2023-04-18 12:11:40.679186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9daba46aba75'
down_revision = 'df98876c986a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewed_posts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'viewed_posts', 'users', ['user_id'], ['id'])
    op.drop_column('viewed_posts', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewed_posts', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_constraint(None, 'viewed_posts', type_='foreignkey')
    op.drop_column('viewed_posts', 'user_id')
    # ### end Alembic commands ###
