"""empty message

Revision ID: c8d801d7e59f
Revises: 01c8908170e0
Create Date: 2023-09-28 00:48:46.185696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d801d7e59f'
down_revision = '01c8908170e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'community_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('community_img', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
