"""empty message

Revision ID: 83232a3ad82d
Revises: 976b3ac3a2e6
Create Date: 2023-08-12 15:51:57.669157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83232a3ad82d'
down_revision = '976b3ac3a2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message_reaction')
    # ### end Alembic commands ###
