"""empty message

Revision ID: b110ee53be8c
Revises: b737c93489db
Create Date: 2023-01-28 04:27:42.245079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b110ee53be8c'
down_revision = 'b737c93489db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('about', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
