"""empty message

Revision ID: 818fd9e40607
Revises: b96d82202e98
Create Date: 2023-09-01 03:43:12.340906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818fd9e40607'
down_revision = 'b96d82202e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('background_img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'background_img')
    # ### end Alembic commands ###
