"""empty message

Revision ID: 424d39e77059
Revises: b63715a46899
Create Date: 2023-01-19 01:43:59.497282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424d39e77059'
down_revision = 'b63715a46899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.create_foreign_key(None, 'communities', 'users', ['user_id'], ['id'])
    op.drop_column('communities', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('owner_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.create_foreign_key(None, 'communities', 'users', ['owner_id'], ['id'])
    op.drop_column('communities', 'user_id')
    # ### end Alembic commands ###