"""empty message

Revision ID: 92b3e2220c3c
Revises: c7170e7418c1
Create Date: 2023-01-28 04:52:10.129884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b3e2220c3c'
down_revision = 'c7170e7418c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banner_img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_img')
    # ### end Alembic commands ###
