"""empty message

Revision ID: 2f67ac94bc1e
Revises: 92b3e2220c3c
Create Date: 2023-01-28 06:56:42.315805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f67ac94bc1e'
down_revision = '92b3e2220c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('followers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'followers')
    # ### end Alembic commands ###
