"""empty message

Revision ID: a38d7ea4b4ec
Revises: d2f054624940
Create Date: 2023-04-23 09:11:11.321107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38d7ea4b4ec'
down_revision = 'd2f054624940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_threads', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('message_threads', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_threads', 'updated_at')
    op.drop_column('message_threads', 'created_at')
    # ### end Alembic commands ###
