"""empty message

Revision ID: af28779e8b1b
Revises: c3660c18851b
Create Date: 2023-01-16 18:50:25.789461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af28779e8b1b'
down_revision = 'c3660c18851b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('community_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'communities', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'community_id')
    # ### end Alembic commands ###