"""empty message

Revision ID: 4f523c68c657
Revises: b15f8a3feaa8
Create Date: 2023-08-22 05:24:34.618512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f523c68c657'
down_revision = 'b15f8a3feaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preview_community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('base_color', sa.String(length=10), nullable=True),
    sa.Column('highlight', sa.String(length=10), nullable=True),
    sa.Column('body_background', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preview_community')
    # ### end Alembic commands ###
