"""add is_seen column to notifications

Revision ID: 008c7ea1bc1b
Revises: 584ab5ceda5e
Create Date: 2025-05-14 17:14:24.628459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008c7ea1bc1b'
down_revision = '584ab5ceda5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_seen', sa.Boolean(), nullable=False, server_default=sa.text("FALSE")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_seen')
    # ### end Alembic commands ###
